/**
 * This code was generated by Builder.io.
 */
import React from "react";

export const ImageSection: React.FC = () => {
  return (
    <div className="flex flex-col ml-5 w-[38%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow max-md:mt-10 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/022fbe28f0cafc061dfeefcdc5c07c6c573948f7068a105b60435c27ad1ba286?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
          className="object-contain w-full aspect-[0.31] max-md:max-w-full"
          alt="Decorative image 1"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/1e0658404f76e765b177f586cdc3f774b7da6f079eb88a6ad96734175e648531?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
          className="object-contain mt-9 w-full aspect-[0.75] max-md:max-w-full"
          alt="Decorative image 2"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/334cf0e5514a824359f3b08eec020004acf845ebba50ca81acb25b257bc5b271?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
          className="object-contain mt-10 w-full aspect-[0.51] max-md:max-w-full"
          alt="Decorative image 3"
        />
      </div>
    </div>
  );
};
