/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SectionHeaderProps {
  title: string;
}

export const SectionHeader: React.FC<SectionHeaderProps> = ({ title }) => {
  return (
    <div className="flex flex-col w-full text-xl font-bold text-stone-800 max-md:max-w-full">
      <div className="flex flex-col items-start w-full min-h-[30px] max-md:max-w-full">
        <div className="flex overflow-hidden gap-4 items-center">
          <div className="self-stretch my-auto">{title}</div>
          <div className="flex shrink-0 self-stretch my-auto h-0.5 bg-stone-800 w-[73px]" />
        </div>
      </div>
    </div>
  );
};
