/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { SectionHeader } from "./SectionHeader";
import { InfoRow } from "./InfoRow";
import { ProgressBar } from "./ProgressBar";
import { ImageSection } from "./ImageSection";
import { NavigationButtons } from "./NavigationButtons";

interface SummaryPageProps {
  // Add any necessary props here
}

export const SummaryPage: React.FC<SummaryPageProps> = () => {
  return (
    <main className="flex flex-col">
      <header className="self-center text-4xl font-bold text-center text-stone-800">
        CR<span className="italic">E</span>ATE YOUR TRADE <br /> BUYER{" "}
        <span className="">A</span>CCOUNT
      </header>
      <section className="flex flex-col mt-24 max-w-full w-[433px] max-md:mt-10">
        <h2 className="w-full text-4xl font-bold whitespace-nowrap rounded-none text-stone-800 max-md:pr-5">
          Summary
        </h2>
        <ProgressBar current={7} total={7} />
      </section>
      <div className="mt-14 max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[62%] max-md:ml-0 max-md:w-full">
            <SectionHeader title="Manila FAME" />
            <InfoRow
              label="Registered Company Name:"
              value="Quanby Solutions Inc."
            />
            <InfoRow
              label="Company Email Address:"
              value="quanbysolutions@gmail.com"
            />
            <InfoRow label="Username:" value="quanby_solutions.inc" />
            <InfoRow
              label="Business Registered in the Philippines:"
              value="YES"
            />
            <InfoRow
              label="Past Participation in Manila FAME Editions:"
              value="NO"
            />

            <SectionHeader title="Contact Details" />
            <h3 className="font-medium max-md:max-w-full">
              Business Information
            </h3>
            <InfoRow
              label="Registered Company Name:"
              value="Quanby Solutions Inc."
            />
            <InfoRow
              label="Company Email Address:"
              value="quanbysolutions@gmail.com"
            />
            <InfoRow label="Brand Name:" value="quanby_solutions.inc" />
            <InfoRow label="Telephone Number (Landline)" value="YES" />
            <InfoRow label="Mobile Number:" value="NO" />
            <InfoRow label="Office Address:" value="YES" />
            <InfoRow label="Factory Address:" value="YES" />

            <h3 className="font-medium max-md:max-w-full">
              Online and Social Media Presence
            </h3>
            <InfoRow label="Website:" value="Quanby Solutions Inc." />
            <InfoRow label="Facebook:" value="quanbysolutions@gmail.com" />
            <InfoRow label="Instagram:" value="quanby_solutions.inc" />
            <InfoRow label="X:" value="YES" />
            <InfoRow label="LinkedIn:" value="NO" />
            <InfoRow label="International Online Directory:" value="NO" />

            <h3 className="font-medium max-md:max-w-full">Contact Person(s)</h3>
            <InfoRow label="Name: (Primary)" value="Quanby Solutions Inc." />
            <InfoRow label="Designation:" value="quanbysolutions@gmail.com" />
            <InfoRow label="Email Address:" value="quanby_solutions.inc" />
            <InfoRow label="Mobile Number:" value="YES" />
            <InfoRow label="App/s Linked to Mobile Number:" value="NO" />

            <SectionHeader title="Business Information" />
            <h3 className="font-medium max-md:max-w-full">
              Business Registration
            </h3>
            <InfoRow label="Year Established:" value="Quanby Solutions Inc." />
            <InfoRow
              label="Validity of Business/Mayor's Permit"
              value="quanbysolutions@gmail.com"
            />
            <InfoRow
              label="Industry Affiliations:"
              value="quanby_solutions.inc"
            />

            <h4 className="font-bold px-8 py-3.5 min-w-[240px] w-[399px] max-md:px-5">
              Number of Workers
            </h4>
            <div className="flex flex-col px-8 w-full max-md:px-5 max-md:max-w-full">
              <InfoRow label="Direct Workers:" value="NO" />
              <InfoRow label="Indirect Workers:" value="YES" />
            </div>

            <h3 className="font-medium max-md:max-w-full">
              Industry Representation
            </h3>
            <InfoRow
              label="Type of Organization:"
              value="Quanby Solutions Inc."
            />
            <InfoRow
              label="Trade Experience:"
              value="quanbysolutions@gmail.com"
            />
            <InfoRow
              label="Type of Orders Accepted:"
              value="quanby_solutions.inc"
            />
            <InfoRow label="Nature of Business:" value="YES" />
            <InfoRow label="Market Segment:" value="NO" />
            <InfoRow label="Product Category:" value="NO" />
            <InfoRow label="Product Sub-category:" value="NO" />
            <InfoRow label="Target Buyers:" value="NO" />

            <SectionHeader title="Uploaded Documents" />
            <InfoRow
              label="For PHILEXPORT Members:"
              value="Quanby Solutions Inc."
            />
            <InfoRow
              label="Financial Statement:"
              value="quanbysolutions@gmail.com"
            />
            <InfoRow
              label="Mayor's / Business Permit:"
              value="quanby_solutions.inc"
            />
            <InfoRow label="Brand Story / Write-up:" value="YES" />
            <InfoRow label="Product Photos:" value="NO" />

            <SectionHeader title="Physical Participation" />
            <InfoRow label="Participating in:" value="Quanby Solutions Inc." />
            <InfoRow
              label="Participating as:"
              value="quanbysolutions@gmail.com"
            />
            <InfoRow
              label="Participation Package:"
              value="quanby_solutions.inc"
            />
            <InfoRow label="Booth Size Requirements:" value="NO" />
            <InfoRow label="Space / Booth Cost:" value="YES" />
            <InfoRow label="FAME+ Subscription Fee:" value="NO" />
            <InfoRow label="Participation Package Cost Estimate:" value="NO" />
            <InfoRow
              label="Name to be used in event promotional materials and will appear in fascia board:"
              value="NO"
            />
            <InfoRow
              label="Majority (>80%) of products to be showcased in Manila FAME+:"
              value="NO"
            />

            <NavigationButtons />
          </div>
          <ImageSection />
        </div>
      </div>
    </main>
  );
};
