/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface CheckboxFieldProps {
  id: string;
  label: React.ReactNode;
}

const CheckboxField: React.FC<CheckboxFieldProps> = ({ id, label }) => {
  return (
    <div className="flex flex-col justify-center items-end mt-11 w-full max-w-[554px] max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-wrap gap-4 items-center w-full">
        <input type="checkbox" id={id} className="sr-only" />
        <label htmlFor={id} className="flex items-center cursor-pointer">
          <span className="flex flex-col justify-center items-center self-stretch px-0.5 my-auto w-5 h-5 bg-stone-600 min-h-[20px] mr-4">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/83a1ffcd31655e8655c547ba8bef01869fae6ede41c6651cf99f2e810949e7e4?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
              alt=""
              className="object-contain aspect-[1.25] w-[15px]"
            />
          </span>
          <span className="self-stretch my-auto text-sm font-medium leading-7 text-zinc-600 w-[223px]">
            {label}
          </span>
        </label>
      </div>
    </div>
  );
};

export default CheckboxField;
