/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProgressBar from "./ProgressBar";
import InputField from "./InputField";
import RadioGroup from "./RadioGroup";
import CheckboxField from "./CheckboxField";
import NavigationButtons from "./NavigationButtons";

interface ExhibitorRegistrationProps {}

const ExhibitorRegistration: React.FC<ExhibitorRegistrationProps> = () => {
  return (
    <main className="flex overflow-hidden flex-col">
      <header className="self-center text-4xl font-bold text-center text-stone-800 max-md:max-w-full">
        CR<span className="italic">E</span>ATE YOUR EXHIBITOR <br />
        <span className="">A</span>CCOUNT
      </header>
      <section className="flex flex-col justify-center mt-24 max-w-full w-[555px] max-md:mt-10">
        <div className="flex flex-col items-start w-full max-md:max-w-full">
          <div className="flex flex-col max-w-full w-[433px]">
            <h1 className="w-full text-4xl font-bold rounded-none text-stone-800 max-md:pr-5">
              Account Registration
            </h1>
            <ProgressBar current={2} total={7} />
          </div>
        </div>
        <form className="mt-8 max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col justify-center w-full max-md:mt-10 max-md:max-w-full">
                <div className="flex flex-col w-full font-medium max-md:max-w-full">
                  <InputField
                    label="Registered Complete Company Name*"
                    type="text"
                    id="companyName"
                    required
                  />
                  <InputField
                    label="Company Email Address*"
                    type="email"
                    id="companyEmail"
                    required
                    helperText={[
                      "Make sure you have access to this email address.",
                      "All system-generated notifications will be sent to this email address.",
                    ]}
                  />
                  <InputField
                    label="Username*"
                    type="text"
                    id="username"
                    required
                  />
                  <InputField
                    label="Password*"
                    type="password"
                    id="password"
                    required
                    helperText={[
                      "Password must include alphabets, at least one (1) number, and a special character.",
                      "This will be your password when you login to FAME+ once your account is activated.",
                    ]}
                  />
                  <RadioGroup
                    label="Is your business registered in the Philippines?"
                    name="businessRegistration"
                    options={[
                      { value: "yes", label: "YES (Local)" },
                      { value: "no", label: "NO (Foreign Company)" },
                    ]}
                    helperText={[
                      "Note: Message for foreign company.",
                      "We only accept local companies for this event.",
                    ]}
                  />
                  <RadioGroup
                    label="Have you participated in any physical Manila FAME editions?*"
                    name="previousParticipation"
                    options={[
                      { value: "yes", label: "YES" },
                      { value: "no", label: "NO" },
                    ]}
                    required
                  />
                  <InputField
                    label="Please specify edition*"
                    type="text"
                    id="edition"
                    required
                  />
                </div>
                <CheckboxField
                  id="termsAgreement"
                  label={
                    <>
                      I agree to the{" "}
                      <span className="font-semibold underline text-stone-600">
                        Terms and Conditions.
                      </span>
                    </>
                  }
                />
                <NavigationButtons />
              </div>
            </div>
            <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/d122bf4c3e3f9824c0fc96ddec331029057f47792dab93297bee98a669ff2cdd?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
                alt="Exhibitor registration illustration"
                className="object-contain grow w-full aspect-[0.69] max-md:mt-10 max-md:max-w-full"
              />
            </div>
          </div>
        </form>
      </section>
    </main>
  );
};

export default ExhibitorRegistration;
