/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface InputFieldProps {
  label: string;
  type: string;
  id: string;
  required?: boolean;
  helperText?: string[];
}

const InputField: React.FC<InputFieldProps> = ({
  label,
  type,
  id,
  required = false,
  helperText,
}) => {
  return (
    <div className="flex flex-col mt-4 w-full">
      <label htmlFor={id} className="sr-only">
        {label}
      </label>
      <input
        type={type}
        id={id}
        required={required}
        className="overflow-hidden px-6 py-3.5 w-full text-lg leading-loose border border-solid border-stone-800 text-stone-800 text-opacity-70 max-md:px-5"
        placeholder={label}
      />
      {helperText && (
        <div className="flex flex-col items-start w-full text-sm leading-7 text-center text-black max-md:max-w-full">
          {helperText.map((text, index) => (
            <div key={index} className="max-md:max-w-full">
              {text}
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default InputField;
