/**
 * This code was generated by Builder.io.
 */
import React from "react";

const NavigationButtons: React.FC = () => {
  return (
    <div className="flex flex-wrap gap-10 justify-between items-center mt-11 max-w-full text-lg font-bold leading-loose text-white whitespace-nowrap w-[554px] max-md:mt-10">
      <button
        className="flex flex-col self-stretch my-auto w-[53px] h-[53px] bg-stone-600 items-center justify-center"
        aria-label="Previous"
      >
        &lt;
      </button>
      <button className="flex flex-col self-stretch my-auto w-[171px] bg-stone-600 items-center justify-center py-3.5">
        NEXT
      </button>
    </div>
  );
};

export default NavigationButtons;
