/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface RadioOption {
  value: string;
  label: string;
}

interface RadioGroupProps {
  label: string;
  name: string;
  options: RadioOption[];
  required?: boolean;
  helperText?: string[];
}

const RadioGroup: React.FC<RadioGroupProps> = ({
  label,
  name,
  options,
  required = false,
  helperText,
}) => {
  return (
    <div className="flex flex-col mt-4 w-full text-stone-800 text-opacity-70 max-md:max-w-full">
      <div className="text-lg leading-loose max-md:max-w-full">{label}</div>
      <div className="flex flex-col justify-center items-start px-8 mt-1.5 w-full text-base leading-7 max-md:px-5 max-md:max-w-full">
        {options.map((option, index) => (
          <div key={index} className="flex flex-wrap gap-1.5 items-center">
            <input
              type="radio"
              id={`${name}-${option.value}`}
              name={name}
              value={option.value}
              required={required}
              className="sr-only"
            />
            <label
              htmlFor={`${name}-${option.value}`}
              className="flex items-center cursor-pointer"
            >
              <span className="flex shrink-0 self-stretch my-auto rounded-full border border-black border-solid h-[18px] w-[18px] mr-1.5"></span>
              <span className="self-stretch my-auto">{option.label}</span>
            </label>
          </div>
        ))}
      </div>
      {helperText && (
        <div className="flex flex-col justify-center px-8 w-full text-sm leading-7 text-black max-md:px-5 max-md:max-w-full">
          {helperText.map((text, index) => (
            <div key={index} className="max-md:max-w-full">
              {text}
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default RadioGroup;
