/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ContactPersonForm: React.FC = () => {
  return (
    <form className="flex flex-col mt-8 w-full max-md:max-w-full">
      <div className="flex overflow-hidden gap-4 items-center self-start text-xl font-bold text-stone-800">
        <h3 className="self-stretch my-auto">Contact Person(s)</h3>
        <div className="flex shrink-0 self-stretch my-auto h-0.5 bg-stone-800 w-[73px]" />
      </div>
      <div className="mt-2.5 text-lg font-medium leading-7 text-stone-800 text-opacity-70 max-md:max-w-full">
        <span className="font-bold">PRIMARY CONTACT</span>
        <br />
        (CEO/Owner and/or must be a decision maker.)
      </div>
      <div className="flex flex-col mt-2.5 max-w-full text-lg font-medium leading-loose text-stone-800 text-opacity-70 w-[555px]">
        <div className="flex overflow-hidden flex-col justify-center px-6 py-3.5 w-full border border-solid border-stone-800 max-md:px-5 max-md:max-w-full">
          <label htmlFor="firstName" className="sr-only">
            First Name
          </label>
          <input
            type="text"
            id="firstName"
            name="firstName"
            placeholder="First Name*"
            className="w-full bg-transparent"
          />
        </div>
      </div>
      <div className="flex flex-col mt-2.5 max-w-full text-lg font-medium leading-loose text-stone-800 text-opacity-70 w-[555px]">
        <div className="flex overflow-hidden flex-col justify-center px-6 py-3.5 w-full border border-solid border-stone-800 max-md:px-5 max-md:max-w-full">
          <label htmlFor="middleInitial" className="sr-only">
            Middle Initial
          </label>
          <input
            type="text"
            id="middleInitial"
            name="middleInitial"
            placeholder="Middle Initial"
            className="w-full bg-transparent"
          />
        </div>
      </div>
      <div className="flex flex-col mt-2.5 max-w-full text-lg font-medium leading-loose text-stone-800 text-opacity-70 w-[555px]">
        <div className="flex overflow-hidden flex-col justify-center px-6 py-3.5 w-full border border-solid border-stone-800 max-md:px-5 max-md:max-w-full">
          <label htmlFor="lastName" className="sr-only">
            Last Name
          </label>
          <input
            type="text"
            id="lastName"
            name="lastName"
            placeholder="Last Name*"
            className="w-full bg-transparent"
          />
        </div>
      </div>
      <div className="flex flex-col mt-2.5 max-w-full text-lg font-medium leading-loose whitespace-nowrap text-stone-800 text-opacity-70 w-[555px]">
        <div className="flex overflow-hidden flex-col justify-center px-6 py-3.5 w-full border border-solid border-stone-800 max-md:px-5 max-md:max-w-full">
          <div className="flex flex-wrap gap-10 justify-between items-center max-md:max-w-full">
            <label htmlFor="gender" className="sr-only">
              Gender
            </label>
            <select id="gender" name="gender" className="w-full bg-transparent">
              <option value="">Gender*</option>
              <option value="male">Male</option>
              <option value="female">Female</option>
              <option value="other">Other</option>
            </select>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/3280131ff66335a1b935998099a98140ebb3bf335247a24a9ac8bb15822b6144?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
            />
          </div>
        </div>
      </div>
      <div className="flex overflow-hidden flex-col justify-center px-6 py-3.5 mt-2.5 w-full text-lg font-medium leading-loose whitespace-nowrap border border-solid border-stone-800 max-w-[555px] text-stone-800 text-opacity-70 max-md:px-5 max-md:max-w-full">
        <label htmlFor="designation" className="sr-only">
          Designation
        </label>
        <input
          type="text"
          id="designation"
          name="designation"
          placeholder="Designation*"
          className="w-full bg-transparent"
        />
      </div>
      <div className="flex flex-col justify-center items-center mt-2.5 w-full max-md:max-w-full">
        <div className="flex flex-col max-w-full text-lg font-medium leading-loose text-stone-800 text-opacity-70 w-[555px]">
          <div className="flex overflow-hidden flex-col justify-center px-6 py-3.5 w-full border border-solid border-stone-800 max-md:px-5 max-md:max-w-full">
            <label htmlFor="mobileNumber" className="sr-only">
              Mobile Number
            </label>
            <input
              type="tel"
              id="mobileNumber"
              name="mobileNumber"
              placeholder="Mobile Number*"
              className="w-full bg-transparent"
            />
          </div>
        </div>
        <div className="flex flex-col self-stretch mt-6 w-full max-md:max-w-full">
          <div className="text-lg leading-loose text-stone-800 text-opacity-70 max-md:max-w-full">
            App/s linked to your mobile number
          </div>
          <div className="flex items-center mt-2.5 w-full text-sm font-medium leading-loose whitespace-nowrap text-zinc-600 max-md:max-w-full">
            <label className="flex gap-4 items-center self-stretch my-auto w-[189px]">
              <input
                type="checkbox"
                className="w-5 h-5 border border-solid bg-stone-100 border-zinc-600"
              />
              <span className="self-stretch my-auto w-[497px] max-md:max-w-full">
                Viber
              </span>
            </label>
            <label className="flex gap-4 items-center self-stretch my-auto w-[189px]">
              <input
                type="checkbox"
                className="w-5 h-5 border border-solid bg-stone-100 border-zinc-600"
              />
              <span className="self-stretch my-auto w-[497px] max-md:max-w-full">
                WeChat
              </span>
            </label>
            <label className="flex gap-4 items-center self-stretch my-auto w-[189px]">
              <input
                type="checkbox"
                className="w-5 h-5 border border-solid bg-stone-100 border-zinc-600"
              />
              <span className="self-stretch my-auto w-[497px]">WhatsApp</span>
            </label>
          </div>
        </div>
        <div className="flex flex-col mt-6 max-w-full text-lg font-medium leading-loose text-stone-800 text-opacity-70 w-[555px]">
          <div className="flex overflow-hidden flex-col justify-center px-6 py-3.5 w-full border border-solid border-stone-800 max-md:px-5 max-md:max-w-full">
            <label htmlFor="emailAddress" className="sr-only">
              Email Address
            </label>
            <input
              type="email"
              id="emailAddress"
              name="emailAddress"
              placeholder="Email Address*"
              className="w-full bg-transparent"
            />
          </div>
        </div>
        <div className="flex flex-col mt-6 w-full text-lg font-bold leading-loose text-white max-w-[555px] max-md:max-w-full">
          <button
            type="button"
            className="gap-2.5 self-stretch px-12 py-3.5 bg-stone-600 min-h-[53px] max-md:px-5"
          >
            ADD A SECONDARY CONTACT PERSON
          </button>
        </div>
      </div>
    </form>
  );
};

export default ContactPersonForm;
