/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ContactForm from "./ContactForm";
import AddressForm from "./AddressForm";
import SocialMediaForm from "./SocialMediaForm";
import ContactPersonForm from "./ContactPersonForm";
import NavigationButtons from "./NavigationButtons";

const ContactDetails: React.FC = () => {
  return (
    <main className="flex flex-col items-start pr-20 max-md:pr-5">
      <section className="flex flex-col ml-40 max-w-full w-[875px]">
        <h1 className="self-end text-4xl font-bold text-center text-stone-800 max-md:max-w-full">
          CR<span className="italic">E</span>ATE YOUR EXHIBITOR <br />
          <span>A</span>CCOUNT
        </h1>
        <div className="flex flex-col justify-center mt-24 max-w-full w-[555px] max-md:mt-10">
          <div className="flex flex-col items-start w-full max-md:max-w-full">
            <div className="flex flex-col max-w-full w-[433px]">
              <h2 className="w-full text-4xl font-bold rounded-none text-stone-800 max-md:pr-5">
                Contact Details
              </h2>
              <div className="flex flex-col justify-center mt-5 max-w-full w-[279px]">
                <div className="flex flex-col self-center w-full">
                  <div className="flex flex-col items-start bg-neutral-200 max-md:pr-5">
                    <div className="flex shrink-0 h-1 bg-stone-600 w-[120px]" />
                  </div>
                </div>
                <div className="mt-2 text-xs leading-7 text-center text-neutral-400">
                  <span className="text-lg font-medium leading-7 text-stone-800">
                    03
                  </span>{" "}
                  /{" "}
                  <span className="text-base leading-7 text-neutral-400">
                    07
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="mt-8 w-full max-w-[1275px] max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <aside className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow max-md:mt-10 max-md:max-w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/7fcd7f9d9d0b8cf55364b6a9f0a76e739074fd6c9659e5a0b168c88f5b805498?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
                alt=""
                className="object-contain w-full aspect-[0.66] max-md:max-w-full"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/1824a12dea8786d3ea806b1f8647bde06542552088e8e009c0ad0ba49a279a0d?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
                alt=""
                className="object-contain mt-12 w-full aspect-[0.39] max-md:mt-10 max-md:max-w-full"
              />
            </div>
          </aside>
          <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col justify-center w-full max-md:mt-10 max-md:max-w-full">
              <ContactForm />
              <AddressForm title="Office Address" />
              <AddressForm title="Factory Address" />
              <SocialMediaForm />
              <ContactPersonForm />
              <NavigationButtons />
            </div>
          </div>
        </div>
      </div>
    </main>
  );
};

export default ContactDetails;
