/**
 * This code was generated by Builder.io.
 */
import React from "react";

const NavigationButtons: React.FC = () => {
  return (
    <div className="flex flex-wrap gap-10 justify-between items-center self-end mt-11 max-w-full text-lg font-bold leading-loose text-white whitespace-nowrap w-[554px] max-md:mt-10">
      <button
        type="button"
        className="flex flex-col self-stretch my-auto w-[53px]"
      >
        <div className="gap-2.5 self-stretch px-5 bg-stone-600 h-[53px] min-h-[53px] w-[53px] max-md:px-5 flex items-center justify-center">
          &lt;
        </div>
      </button>
      <button
        type="button"
        className="flex flex-col self-stretch my-auto w-[171px]"
      >
        <div className="gap-2.5 self-stretch px-12 py-3.5 bg-stone-600 min-h-[53px] max-md:px-5 flex items-center justify-center">
          NEXT
        </div>
      </button>
    </div>
  );
};

export default NavigationButtons;
