/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SocialMediaForm: React.FC = () => {
  return (
    <form className="flex flex-col mt-8 w-full text-lg max-md:max-w-full">
      <div className="flex overflow-hidden gap-4 items-center self-start text-xl font-bold text-stone-800">
        <h3 className="self-stretch my-auto">
          Online and Social Media Presence
        </h3>
        <div className="flex shrink-0 self-stretch my-auto h-0.5 bg-stone-800 w-[73px]" />
      </div>
      <div className="mt-2.5 font-medium leading-loose text-stone-800 text-opacity-70 max-md:max-w-full">
        Write N/A to fields that are not available.
      </div>
      <div className="flex overflow-hidden flex-wrap gap-6 py-px mt-2.5 w-full leading-loose border border-solid border-stone-800 max-md:max-w-full">
        <div className="overflow-hidden gap-2.5 self-stretch px-4 py-3 font-bold text-white whitespace-nowrap bg-stone-600">
          www.facebook.com/
        </div>
        <label htmlFor="facebook" className="sr-only">
          Company Facebook
        </label>
        <input
          type="text"
          id="facebook"
          name="facebook"
          placeholder="Company Facebook"
          className="flex-auto my-auto font-medium text-stone-800 text-opacity-70 w-[289px] bg-transparent"
        />
      </div>
      <div className="flex overflow-hidden flex-wrap gap-7 py-px mt-2.5 w-full leading-loose border border-solid border-stone-800 max-md:max-w-full">
        <div className="overflow-hidden gap-2.5 self-stretch py-3 pr-3 pl-3 font-bold text-white whitespace-nowrap bg-stone-600">
          www.instagram.com/
        </div>
        <label htmlFor="instagram" className="sr-only">
          Company Instagram
        </label>
        <input
          type="text"
          id="instagram"
          name="instagram"
          placeholder="Company Instagram"
          className="flex-auto my-auto w-72 font-medium text-stone-800 text-opacity-70 bg-transparent"
        />
      </div>
      <div className="flex overflow-hidden flex-wrap gap-6 py-px mt-2.5 w-full leading-loose border border-solid border-stone-800 max-md:max-w-full">
        <div className="overflow-hidden gap-2.5 self-stretch px-4 py-3 font-bold text-white whitespace-nowrap bg-stone-600">
          www.x.com/
        </div>
        <label htmlFor="twitter" className="sr-only">
          Company X
        </label>
        <input
          type="text"
          id="twitter"
          name="twitter"
          placeholder="Company X"
          className="flex-auto my-auto font-medium text-stone-800 text-opacity-70 w-[289px] bg-transparent"
        />
      </div>
      <div className="flex overflow-hidden flex-wrap gap-7 py-px mt-2.5 w-full leading-loose border border-solid border-stone-800 max-md:max-w-full">
        <div className="overflow-hidden gap-2.5 self-stretch px-4 py-3 font-bold text-white whitespace-nowrap bg-stone-600">
          www.linkedin.com/
        </div>
        <label htmlFor="linkedin" className="sr-only">
          Company LinkedIn
        </label>
        <input
          type="text"
          id="linkedin"
          name="linkedin"
          placeholder="Company LinkedIn"
          className="flex-auto my-auto w-72 font-medium text-stone-800 text-opacity-70 bg-transparent"
        />
      </div>
      <div className="flex flex-col mt-2.5 w-full font-medium leading-loose text-stone-800 text-opacity-70 max-md:max-w-full">
        <div className="flex flex-col max-w-full w-[554px]">
          <div className="overflow-hidden px-6 py-3.5 border border-solid border-stone-800 max-md:px-5 max-md:max-w-full">
            <label htmlFor="directory" className="sr-only">
              International Online Directory
            </label>
            <input
              type="text"
              id="directory"
              name="directory"
              placeholder="International Online Directory"
              className="w-full bg-transparent"
            />
          </div>
        </div>
      </div>
    </form>
  );
};

export default SocialMediaForm;
