/**
 * This code was generated by Builder.io.
 */
import React from "react";

const DocumentUpload: React.FC = () => {
  return (
    <section className="flex flex-col w-full max-md:max-w-full">
      <div className="flex overflow-hidden gap-4 items-center self-start text-xl font-bold text-stone-800">
        <h3 className="self-stretch my-auto">Document Upload</h3>
        <div className="flex shrink-0 self-stretch my-auto h-0.5 bg-stone-800 w-[73px]" />
      </div>
      <div className="flex flex-col mt-2.5 w-full min-h-[373px] max-md:max-w-full">
        <div className="flex flex-col w-full text-lg leading-loose max-md:max-w-full">
          <label
            htmlFor="mayorPermit"
            className="font-medium text-stone-800 text-opacity-70 max-md:max-w-full"
          >
            Valid Mayor's or Business Permit*
          </label>
          <div className="flex overflow-hidden flex-wrap gap-6 py-px mt-1.5 w-full border border-solid border-stone-800 max-md:max-w-full">
            <button className="overflow-hidden gap-2.5 self-stretch px-4 py-3 font-bold text-white bg-stone-600">
              Choose File
            </button>
            <span className="flex-auto my-auto font-medium text-stone-800 text-opacity-70 w-[386px]">
              No file chosen
            </span>
          </div>
          <div className="flex flex-col items-start mt-1.5 w-full text-sm font-medium leading-7 text-center text-black max-md:max-w-full">
            <p className="max-md:max-w-full">
              The maximum file size is 2MB per file.
            </p>
            <p className="max-md:max-w-full">
              File types accepted are .doc, .docx, .pdf, .png, .jpg, and .jpeg.
            </p>
          </div>
        </div>
        <div className="flex flex-col mt-4 w-full font-medium text-stone-800 text-opacity-70 max-md:max-w-full">
          <label className="text-lg leading-loose max-md:max-w-full">
            Brand story or writeup*
          </label>
          <div className="flex flex-col mt-1.5 w-full text-base leading-7 max-md:max-w-full">
            <div className="flex flex-wrap gap-10 items-center pr-6 pl-8 w-full max-md:px-5 max-md:max-w-full">
              <label className="flex flex-wrap gap-1.5 items-center self-stretch my-auto">
                <input type="radio" name="brandStory" className="sr-only" />
                <span className="flex shrink-0 self-stretch my-auto rounded-full border border-black border-solid h-[18px] w-[18px]" />
                <span className="self-stretch my-auto">
                  Upload brand story or writeup
                </span>
              </label>
              <label className="flex flex-wrap gap-1.5 items-center self-stretch my-auto">
                <input type="radio" name="brandStory" className="sr-only" />
                <span className="flex shrink-0 self-stretch my-auto rounded-full bg-stone-600 h-[18px] w-[18px]" />
                <span className="self-stretch my-auto">
                  Write brand story or writeup
                </span>
              </label>
            </div>
          </div>
        </div>
        <textarea className="flex mt-4 w-full border border-solid border-stone-800 min-h-[143px] max-md:max-w-full" />
      </div>
    </section>
  );
};

export default DocumentUpload;
