/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProgressBar from "./ProgressBar";
import DocumentUpload from "./DocumentUpload";
import ProductPhotos from "./ProductPhotos";
import NavigationButtons from "./NavigationButtons";

const ExhibitorAccount: React.FC = () => {
  return (
    <main className="flex overflow-hidden flex-col">
      <div className="flex flex-col self-center max-w-full w-[794px]">
        <h1 className="self-end text-4xl font-bold text-center text-stone-800 max-md:max-w-full">
          CR<span className="italic">E</span>ATE YOUR EXHIBITOR <br />
          <span>A</span>CCOUNT
        </h1>
        <section className="flex flex-col mt-24 max-w-full w-[433px] max-md:mt-10">
          <h2 className="w-full text-4xl font-bold rounded-none text-stone-800 max-md:pr-5">
            Upload Files
          </h2>
          <ProgressBar current={5} total={7} />
        </section>
      </div>
      <div className="mt-8 w-full max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow max-md:mt-10 max-md:max-w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/3c29ae1e77f7f9d8a59b4726db609e5ed3ef58e42000d1e567aff2488df37243?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
                alt="Exhibitor account illustration"
                className="object-contain w-full aspect-[1.52] max-md:max-w-full"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/5ed382ff1597e4d8604b03523d756c9175984249243d3b6cc33a70bcf3eab732?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
                alt="Additional exhibitor account illustration"
                className="object-contain mt-5 w-full aspect-[1.88] max-md:max-w-full"
              />
            </div>
          </div>
          <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col justify-center w-full max-md:mt-10 max-md:max-w-full">
              <div className="flex flex-col w-full max-md:max-w-full">
                <div className="flex flex-col w-full max-md:max-w-full">
                  <div className="flex flex-col w-full max-w-[554px] min-h-[413px] max-md:max-w-full">
                    <DocumentUpload />
                    <ProductPhotos />
                    <NavigationButtons />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
};

export default ExhibitorAccount;
