/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { CheckboxGroup } from "./CheckboxGroup";
import { InputField } from "./InputField";
import { RadioGroup } from "./RadioGroup";
import { ProgressBar } from "./ProgressBar";
import { SectionTitle } from "./SectionTitle";
import { FileUpload } from "./FileUpload";

interface BusinessInformationProps {}

export const BusinessInformation: React.FC<BusinessInformationProps> = () => {
  return (
    <main className="flex overflow-hidden flex-col">
      <header className="self-center text-4xl font-bold text-center text-stone-800 max-md:max-w-full">
        CR<span className="italic">E</span>ATE YOUR EXHIBITOR <br />
        <span className="">A</span>CCOUNT
      </header>
      <section className="flex flex-col justify-center mt-24 max-w-full w-[555px] max-md:mt-10">
        <h2 className="w-full text-4xl font-bold rounded-none text-stone-800 max-md:pr-5">
          Business Information
        </h2>
        <ProgressBar current={4} total={7} />
      </section>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/30eed9d260c55c8336e0cc4785163cc4ec8f01c1ad05d483d1f58825ce254a3e?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
        alt=""
        className="object-contain mt-8 w-full aspect-[3.46] max-md:max-w-full"
      />
      <div className="mt-24 w-full max-w-[1130px] max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <SectionTitle title="Business Registration" />
            <InputField label="Year Established*" />
            <InputField label="Validity of Business / Mayor's Permit*" />
            <InputField label="Industry Affiliation / Business Support Organization" />
            <InputField label="Mobile Number*" />
            <RadioGroup
              title="COMPANY SIZE"
              description="Total company assets in Philippine Peso."
              options={[
                "Micro (Php 3M and Below)",
                "Small (Php 3M - 15M)",
                "Medium (PhP 15M - 100M)",
                "Large (Above Php100M)",
              ]}
              selectedIndex={1}
            />
            <FileUpload
              title="Financial Statement"
              description="If available, please provide your company's latest financial statement for validation purposes"
              fileTypes=".doc, .docx, .pdf, .png, .jpg, and .jpeg"
              maxSize="2MB"
            />
            <div className="flex flex-col mt-4 w-full text-lg text-stone-800 text-opacity-70 max-md:max-w-full">
              <div className="font-bold leading-7 max-md:max-w-full">
                NUMBER OF WORKERS <br />
                <span className="">
                  {" "}
                  Input numbers must be lower than one (1).{" "}
                </span>
              </div>
              <div className="flex flex-wrap gap-4 items-start mt-1.5 font-medium leading-loose max-md:max-w-full">
                <InputField label="Direct Workers*" />
                <InputField label="Indirect Workers / Subcontractors" />
              </div>
            </div>
            <SectionTitle title="Industry Representation" />
            <RadioGroup
              title="Type of Organization / Representation*"
              options={[
                "Single Proprietorship",
                "Corporation",
                "Government",
                "Non-Government Organization",
                "Trade Promotion Office / Embassy",
                "School / University / Academe",
                "Partnership",
                "Foundation / Cooperative",
                "Limited Liability Corporation (LLC)",
                "One Person Corporation (OPC)",
                "Independent Designer / Artist",
                "Allied Industry / Service Supplier",
              ]}
              selectedIndex={3}
            />
            <RadioGroup
              title="Nature of Business*"
              options={[
                "Manufacturing - Direct Exporter",
                "Manufacturing - Indirect Exporter",
                "Trading",
                "Trade Association / Business Support Organization",
                "Others",
              ]}
              selectedIndex={2}
            />
            <RadioGroup
              title="Trade Experience*"
              description="Do you have export experience (direct/indirect)?"
              options={["Yes", "No"]}
              selectedIndex={0}
            />
            <InputField label="Please indicate the top country or countries you export to." />
            <CheckboxGroup
              title="Types of Orders Accepted*"
              description="You may select multiple answers if applicable."
              options={[
                "Export - small quantity",
                "Export - large volume",
                "Domestic - small quantity",
                "Domestic - large volume",
                "Retail - domestic shipping",
                "Retail - international shipping",
              ]}
              selectedIndexes={[0]}
            />
            <RadioGroup
              title="Market Segment*"
              description="You may select multiple answers if applicable."
              options={[
                "Exclusively high-end market",
                "Exclusively low-end market",
                "Middle to high-end market",
                "Middle to low-end market",
              ]}
              selectedIndex={0}
            />
          </div>
          <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
            <SectionTitle title="Product Category" />
            <p className="mt-2.5 text-lg font-medium leading-loose text-stone-800 text-opacity-70 max-md:max-w-full">
              Please choose at least one.
            </p>
            <CheckboxGroup
              title="Home Decor & Houseware"
              options={[
                "Art Installation",
                "Sculptures",
                "Painting",
                "Wall Art",
                "Architectural Fittings",
                "Baskets & Storage",
                "Candleholders",
                "Decorative Boxes",
                "Decorative Figurines",
                "Garden & Outdoor Accessories",
                "Home Textiles",
                "Jars & Vases",
                "Kitchenware",
                "Mirrors & Mirror Frames",
                "Pet Furniture",
                "Rugs and Carpets",
                "Tabletop Decor",
                "Tableware",
                "Wall Decor & Decorative Panels",
                "Wall Covers & Cladding",
                "Window Blinds",
                "Other Home Decor",
              ]}
              selectedIndexes={[5, 10, 11, 13]}
            />
            <CheckboxGroup
              title="Beauty and Wellness"
              options={[
                "Bath Products",
                "Cosmetics",
                "Hand And Body Lotion",
                "Fragrances",
                "Other Beauty and Wellness",
              ]}
              selectedIndexes={[0]}
            />
            <CheckboxGroup
              title="Festive and Seasonal Decor"
              options={[
                "Holiday-themed Tabletops",
                "Ornaments & Hangings",
                "Seasonal Candles & Candleholders",
                "Seasonal Figurines",
                "Wreaths / Garlands",
                "Other Festive / Seasonal Decor",
              ]}
              selectedIndexes={[1]}
            />
            <CheckboxGroup
              title="Fashion"
              options={[
                "Ladies' Wear",
                "Children's Wear",
                "Men's Wear",
                "Costume Jewelry",
                "Fine Jewelry",
                "Footwear",
                "Bag / Clutch",
                "Fashion Textiles",
                "Others Fashion",
                "Fashion Complements (Belt, Hat, Headband, Scarf, Gloves)",
              ]}
              selectedIndexes={[1]}
            />
            <CheckboxGroup
              title="Furniture"
              options={[
                "Indoor Furniture",
                "Kids Furniture",
                "Outdoor Furniture",
                "Other Furniture",
              ]}
              selectedIndexes={[3]}
            />
            <CheckboxGroup
              title="Gifts"
              options={[
                "Collectibles",
                "Desk Accessories",
                "Gift Boxes & Packaging Gifts",
                "Gift Candles & Votives",
                "Party Products",
                "Pet Accessories",
                "Personal Care, Beauty and Wellness Products",
                "Picture Frames",
                "Toys & Games",
                "Other Gifts",
              ]}
              selectedIndexes={[5]}
            />
            <CheckboxGroup
              title="Lamps and Lighting"
              options={[
                "Technical & Electrical",
                "Outdoor Lighting",
                "Indoor Lighting",
              ]}
              selectedIndexes={[]}
            />
          </div>
        </div>
      </div>
      <nav className="flex flex-wrap gap-10 justify-between items-center mt-16 text-lg font-bold leading-loose text-white whitespace-nowrap max-md:mt-10 max-md:max-w-full">
        <button className="flex flex-col self-stretch my-auto w-[53px]">
          <div className="gap-2.5 self-stretch px-5 bg-stone-600 h-[53px] min-h-[53px] w-[53px] max-md:px-5">
            &lt;
          </div>
        </button>
        <button className="flex flex-col self-stretch my-auto w-[171px]">
          <div className="gap-2.5 self-stretch px-12 py-3.5 bg-stone-600 min-h-[53px] max-md:px-5">
            NEXT
          </div>
        </button>
      </nav>
    </main>
  );
};
