/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface CheckboxGroupProps {
  title: string;
  description?: string;
  options: string[];
  selectedIndexes: number[];
}

export const CheckboxGroup: React.FC<CheckboxGroupProps> = ({
  title,
  description,
  options,
  selectedIndexes,
}) => {
  return (
    <div className="flex flex-col mt-5 w-full max-md:max-w-full">
      <h3 className="text-lg font-medium leading-loose text-stone-800 text-opacity-70 max-md:max-w-full">
        {title}
      </h3>
      {description && (
        <p className="mt-1 text-base font-medium text-stone-800 text-opacity-70">
          {description}
        </p>
      )}
      <div className="flex flex-col px-8 mt-2.5 max-w-full w-[533px] max-md:px-5">
        {options.map((option, index) => (
          <div
            key={index}
            className="flex gap-4 items-center mt-2 w-full text-sm font-medium leading-loose text-zinc-600 max-md:max-w-full"
          >
            <div
              className={`flex shrink-0 self-stretch my-auto w-5 h-5 ${
                selectedIndexes.includes(index)
                  ? "bg-stone-600"
                  : "border border-solid bg-stone-100 border-zinc-600"
              }`}
            >
              {selectedIndexes.includes(index) && (
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/68fc4490fcc46110f5670668de34743a4d855b8b9672d0b0a4c3daaac558e985?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
                  alt=""
                  className="object-contain aspect-[1.25] w-[15px]"
                />
              )}
            </div>
            <div className="self-stretch my-auto w-[497px] max-md:max-w-full">
              {option}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
