/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface FileUploadProps {
  title: string;
  description: string;
  fileTypes: string;
  maxSize: string;
}

export const FileUpload: React.FC<FileUploadProps> = ({
  title,
  description,
  fileTypes,
  maxSize,
}) => {
  return (
    <div className="flex flex-col mt-4 w-full max-md:max-w-full">
      <h3 className="text-lg font-medium leading-loose text-stone-800 text-opacity-70 max-md:max-w-full">
        {title}
      </h3>
      <div className="flex flex-col mt-1.5 w-full leading-7 max-md:max-w-full">
        <div className="flex flex-wrap gap-10 items-center px-8 w-full text-base font-medium text-stone-800 text-opacity-70 max-md:px-5 max-md:max-w-full">
          <div className="flex flex-wrap gap-1.5 items-center self-stretch my-auto">
            <div className="flex shrink-0 self-stretch my-auto rounded-full bg-stone-600 h-[18px] w-[18px]" />
            <div className="self-stretch my-auto">
              Upload financial statement
            </div>
          </div>
          <div className="flex flex-wrap gap-1.5 items-center self-stretch my-auto">
            <div className="flex shrink-0 self-stretch my-auto rounded-full border border-black border-solid h-[18px] w-[18px]" />
            <div className="self-stretch my-auto">No financial statement</div>
          </div>
        </div>
        <div className="flex flex-col items-start mt-4 w-full text-sm font-medium text-center text-black max-md:max-w-full">
          <p className="max-md:max-w-full">{description}</p>
          <p className="max-md:max-w-full">
            File types accepted are {fileTypes}. Maximum file size accepted is{" "}
            {maxSize}.
          </p>
        </div>
        <div className="flex overflow-hidden flex-wrap gap-6 py-px mt-4 w-full text-lg leading-loose border border-solid border-stone-800 max-md:max-w-full">
          <button className="overflow-hidden gap-2.5 self-stretch px-4 py-3 font-bold text-white bg-stone-600">
            Choose File
          </button>
          <div className="flex-auto my-auto font-medium text-stone-800 text-opacity-70 w-[387px]">
            No file chosen
          </div>
        </div>
      </div>
    </div>
  );
};
