/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface InputFieldProps {
  label: string;
}

export const InputField: React.FC<InputFieldProps> = ({ label }) => {
  return (
    <div className="flex flex-col mt-4 w-full text-lg font-medium leading-loose text-stone-800 text-opacity-70">
      <div className="flex flex-col w-full max-md:max-w-full">
        <div className="flex flex-col w-full max-md:max-w-full">
          <div className="flex overflow-hidden flex-wrap gap-5 justify-between px-6 py-3.5 border border-solid border-stone-800 max-md:px-5 max-md:max-w-full">
            <label>{label}</label>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/c985608c73034f0728e984a11fee510fd3fada631924d135801356ac74e61957?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
              alt=""
              className="object-contain shrink-0 my-auto w-6 aspect-square"
            />
          </div>
        </div>
      </div>
    </div>
  );
};
