/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SectionTitleProps {
  title: string;
}

export const SectionTitle: React.FC<SectionTitleProps> = ({ title }) => {
  return (
    <div className="flex overflow-hidden gap-4 items-center self-start text-xl font-bold text-stone-800">
      <h2 className="self-stretch my-auto">{title}</h2>
      <div className="flex shrink-0 self-stretch my-auto h-0.5 bg-stone-800 w-[73px]" />
    </div>
  );
};
