/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ParticipationDetails from "./ParticipationDetails";
import BoothOption from "./BoothOption";
import PhilexportMembership from "./PhilexportMembership";
import ManilaFAMEDetails from "./ManilaFAMEDetails";
import NavigationButtons from "./NavigationButtons";

const ExhibitorAccount: React.FC = () => {
  return (
    <main className="flex flex-col">
      <h1 className="self-center text-4xl font-bold text-center text-stone-800 max-md:max-w-full">
        CR<span className="italic">E</span>ATE YOUR EXHIBITOR <br />
        <span>A</span>CCOUNT
      </h1>

      <ParticipationDetails />

      <section className="mt-20 w-full max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <BoothOption
            title="RAW SPACE ONLY"
            price="PHP 4,000.00"
            subscription="+ Php 30,000.00 FAME+ Subscription"
            description="No inclusions. Demarcation of space ONLY."
            imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/6c1ff50542fe9d162953d06704b9d5cee4890e0777b44d854fc20ff0c44ad5db?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
            isSelected={false}
          />
          <BoothOption
            title="ALUMINUM BOOTH SYSTEM"
            price="PHP 4,900.00"
            subscription="+ Php 30,000.00 FAME+ Subscription"
            description="Inclusions"
            imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/ae0d7d81027310ae7cf67ae047e245cc7b3733f183ef6250802cd555086b68f6?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
            inclusions={[
              "9 sqm. - Dark Gray / Black Carpet",
              "1 lot - Structural Frame",
              "1 unit - Fascia Board with Company Name",
              "1 unit - Trash Bin",
              "1 unit - System Table",
              "2 units - Chair",
              "3 units - Shelving",
              "3 units - Light Bulb with Housing and Wiring",
            ]}
            isSelected={true}
          />
        </div>
      </section>

      <PhilexportMembership />

      <ManilaFAMEDetails />

      <NavigationButtons />
    </main>
  );
};

export default ExhibitorAccount;
