/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ManilaFAMEDetails: React.FC = () => {
  return (
    <section className="flex flex-col justify-center mt-40 max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-col w-full max-md:max-w-full">
        <h2 className="flex flex-col items-start w-full text-xl font-bold text-stone-800 min-h-[30px] max-md:max-w-full">
          <div className="flex overflow-hidden gap-4 items-center">
            <span className="self-stretch my-auto">Manila FAME</span>
            <div className="flex shrink-0 self-stretch my-auto h-0.5 bg-stone-800 w-[73px]" />
          </div>
        </h2>
        <div className="flex flex-col mt-6 w-full text-lg text-stone-800 text-opacity-70 max-md:max-w-full">
          <div className="flex flex-wrap gap-1.5 items-start w-full leading-loose max-md:max-w-full">
            <span className="overflow-hidden grow shrink px-6 py-3.5 font-medium min-w-[240px] w-[270px] max-md:px-5">
              Packaging Name:
            </span>
            <span className="overflow-hidden grow shrink px-6 py-3.5 font-bold border border-solid bg-stone-200 border-stone-800 border-opacity-70 min-w-[240px] w-[698px] max-md:px-5 max-md:max-w-full">
              ALUMINUM BOOTH SYSTEM
            </span>
          </div>
          <div className="flex flex-wrap gap-1.5 items-start mt-4 w-full font-medium leading-loose max-md:max-w-full">
            <label
              htmlFor="booth-size"
              className="overflow-hidden grow shrink px-6 py-3.5 min-w-[240px] w-[270px] max-md:px-5"
            >
              Booth size requirement:
            </label>
            <div className="flex overflow-hidden flex-col grow shrink justify-center px-6 py-3.5 whitespace-nowrap border border-solid border-stone-800 min-w-[240px] w-[698px] max-md:px-5 max-md:max-w-full">
              <select
                id="booth-size"
                className="w-full bg-transparent appearance-none"
              >
                <option>Select</option>
              </select>
            </div>
          </div>
          <div className="flex flex-wrap gap-1.5 items-start mt-4 w-full leading-loose max-md:max-w-full">
            <span className="overflow-hidden grow shrink px-6 py-3.5 font-medium min-w-[240px] w-[270px] max-md:px-5">
              Cost per square meter:
            </span>
            <span className="overflow-hidden grow shrink px-6 py-3.5 font-bold border border-solid bg-stone-200 border-stone-800 border-opacity-70 min-w-[240px] w-[698px] max-md:px-5 max-md:max-w-full">
              PHP 4,900.00
            </span>
          </div>
          <div className="flex flex-wrap gap-1.5 justify-center items-center mt-4 w-full max-md:max-w-full">
            <span className="overflow-hidden grow shrink self-stretch px-6 py-3.5 my-auto font-medium leading-7 min-w-[240px] w-[270px] max-md:pl-5">
              FAME+ Subscription. <br />
              For PHILEXPORT members, our team will review and verify the
              documents you have submitted, and the fee will be waived upon
              authentication.
            </span>
            <span className="overflow-hidden grow shrink self-stretch px-6 py-3.5 my-auto font-bold leading-loose border border-solid bg-stone-200 border-stone-800 border-opacity-70 min-w-[240px] w-[698px] max-md:px-5 max-md:max-w-full">
              PHP 10,000.00
            </span>
          </div>
          <div className="flex flex-wrap gap-1.5 items-start mt-4 w-full leading-loose max-md:max-w-full">
            <span className="overflow-hidden grow shrink px-6 py-3.5 font-medium min-w-[240px] w-[270px] max-md:px-5">
              Cost Estimate:
            </span>
            <span className="overflow-hidden grow shrink px-6 py-3.5 font-bold border border-solid bg-stone-200 border-stone-800 border-opacity-70 min-w-[240px] w-[698px] max-md:px-5 max-md:max-w-full">
              PHP 10,000.00
            </span>
          </div>
          <div className="flex flex-wrap gap-1.5 justify-center items-center mt-4 w-full font-medium max-md:max-w-full">
            <label
              htmlFor="booth-name"
              className="overflow-hidden grow shrink self-stretch px-6 py-3.5 my-auto leading-7 min-w-[240px] w-[270px] max-md:px-5"
            >
              Name to appear in event promotional materials* <br />
              (This name will also be used on the fascia board.)
            </label>
            <input
              type="text"
              id="booth-name"
              className="overflow-hidden grow shrink self-stretch px-6 py-3.5 my-auto leading-loose border border-solid border-stone-800 min-w-[240px] w-[698px] max-md:px-5 max-md:max-w-full"
              placeholder="Please enter booth name"
              aria-label="Enter booth name for promotional materials"
            />
          </div>
          <div className="flex flex-wrap gap-1.5 justify-center items-center mt-4 w-full font-medium max-md:max-w-full">
            <label
              htmlFor="product-category"
              className="overflow-hidden grow shrink self-stretch px-6 py-3.5 my-auto leading-7 min-w-[240px] w-[270px] max-md:px-5"
            >
              Majority (&gt;80%) of products to be showcased in Manila FAME.
            </label>
            <div className="flex overflow-hidden flex-col grow shrink justify-center self-stretch px-6 py-3.5 my-auto leading-loose border border-solid border-stone-800 min-w-[240px] w-[698px] max-md:px-5 max-md:max-w-full">
              <select
                id="product-category"
                className="w-full bg-transparent appearance-none"
              >
                <option>Pick product category</option>
              </select>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default ManilaFAMEDetails;
