/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ParticipationDetails: React.FC = () => {
  return (
    <section className="flex flex-col mt-24 max-w-full w-[433px] max-md:mt-10">
      <h2 className="w-full text-4xl font-bold rounded-none text-stone-800 max-md:pr-5">
        Participation Details
      </h2>
      <div className="flex flex-col justify-center mt-5 max-w-full w-[279px]">
        <div className="flex flex-col self-center w-full">
          <div className="flex flex-col items-start bg-neutral-200 max-md:pr-5">
            <div className="flex shrink-0 h-1 bg-stone-600" />
          </div>
        </div>
        <div className="mt-2 text-xs leading-7 text-center text-neutral-400">
          <span className="text-lg font-medium leading-7 text-stone-800">
            06
          </span>{" "}
          / <span className="text-base leading-7 text-neutral-400">07</span>
        </div>
      </div>
    </section>
  );
};

export default ParticipationDetails;
