/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SelectionFieldProps {
  label: string;
}

export const SelectionField: React.FC<SelectionFieldProps> = ({ label }) => {
  return (
    <div className="flex overflow-hidden flex-col justify-center px-6 py-3.5 mt-4 w-full leading-loose border border-solid border-stone-800 max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-between items-center max-md:max-w-full max-sm:flex max-sm:flex-row">
        <label className="self-stretch my-auto">{label}</label>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/827b99f8232e849b5c0609607d3401e83477c09217b7788a06a97ebb092e809d?placeholderIfAbsent=true&apiKey=bcd25a482c724058b98e564e8bbde85d"
          className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
          alt=""
        />
      </div>
    </div>
  );
};
