// src/interfaces/exhibitor.tsx

export interface ExhibitorInfo {
  website: string;
  twitter: string;
  username: string;
  linkedin: string;
  directory: string;
  firstName: string;
  facebook: string;
  instagram: string;
  boothSize: string;
  boothName: string;
  companySize: string;
  boothOption: string;
  middleInitial: string;
  packagingName: string;
  officeAddress: string;
  spaceBoothCost: string;
  factoryAddress: string;
  participatingIn: string;
  participatingAs: string;
  promotionalName: string;
  productCategory: string;
  brandStoryOption: string;
  brandStoryWriteup: string;
  yearEstablished: string;
  businessMobile: string;
  directWorkers: string;
  indirectWorkers: string;
  organizationType: string;
  natureOfBusiness: string;
  tradeExperience: string;
  exportCountries: string;
  marketSegment: string;
  lastName: string;
  gender: string;
  designation: string;
  mobileNumber: string;
  emailAddress: string;
  phoneNumber: string;
  zipCode: string;
  street: string;
  companyName: string;
  email: string;
  contactPerson: string;
  password: string;
  confirmPassword: string;
  edition: string;
  event: string;
  participationType: string;
  industryAffiliation: string;
  packageCostEstimate: string;
  fameSubscriptionFee: string;
  boothSizeRequirement: string;
  participationPackage: string;
  philexportMembership: string;
  businessPermitValidity: string;
  majorityProductsShowcased: string;
  businessRegisteredInPhilippines: boolean;
  pastParticipation: boolean;
  mobileAppsLinked: boolean;
  philexportMember: boolean;
  viber: boolean;
  weChat: boolean;
  whatsApp: boolean;
  sameAsOfficeAddress: boolean;
  noFactoryAddress: boolean;
  agreeToTerms: boolean;
  orderTypes: string[];
  productPhotos: File[];
  homeDecorCategories: string[];
  financialStatement: File | null;
  mayorPermit: File | null;
  philexportDocument: File | null;
  country: string | number | readonly string[] | undefined;
  region: string | number | readonly string[] | undefined;
  province: string | number | readonly string[] | undefined;
  city: string | number | readonly string[] | undefined;
}
